[project]
name = "recursive-dict"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "datasets>=3.6.0",
    "nltk>=3.9.1",
    "pip>=25.1.1",
    "pybind11>=2.13.6",
    "spacy>=3.8.5",
    "tqdm>=4.67.1",
]
